add side-magnet-angular to post angular
hubergerard/blog-codewise pull request #64
Opened 2022-05-16 12:00 UTC by Lucaversace

2022-05-16 12:38 UTC, hubergerard requested changes

2022-05-16 12:38 UTC, hubergerard commented on _includes/side_magnet_angular.html
> +<!-- <div class="shadow-side-magnet widget">
Supprimer les commentaires

2022-05-16 12:38 UTC, hubergerard commented on _includes/side_magnet_angular.html
> +<!-- <div class="shadow-side-magnet widget">
Et renommer le fichier avec des dash (-)

2022-05-16 12:38 UTC, hubergerard commented on _includes/side_magnet_angular.html
> +        <img id="img-starter" class="mb-3" src="/assets/img/blog/starter-kit/cadeau_starter.png" alt="">
`alt="starter-kit-angular"`

2022-05-16 12:38 UTC, hubergerard commented on _includes/side_magnet_angular.html
> +<div id="side-magnet-angular" style="top: 11.5em;" class="card shadow-side-magnet widget p-3 d-none d-lg-block sticky-top">
Supprimer le inline-style. (classe CSS à la place)

2022-05-16 12:38 UTC, hubergerard commented on assets/css/style.css
> +.border-dashed{
Supprime les classes qui te servent pas pour le magnet (border-dashed et surement d'autres)

2022-05-16 12:38 UTC, hubergerard commented on assets/css/style.css
> +.border-dashed{
Ca évitera des conflits quand on merge

2022-05-16 12:38 UTC, hubergerard commented on assets/css/style.css
> +    position: sticky !important;
Il faut vraiment le important pour ca ? Je pense que ton top : 11.5 em pourrait venir dans cette classe s'il te sert, sinon supprime le

2022-05-16 12:38 UTC, hubergerard commented on assets/css/style.css
> +    box-shadow: 0 5px 30px rgba(0, 0, 0, 0.1);
Tu as repris le box-shadow qu'on utilisait sur le blog ?

2022-05-16 12:38 UTC, hubergerard commented on assets/css/style.css
> +    margin: 0 !important;
besoin du important ?

2022-05-17 08:34 UTC, Lucaversace commented on assets/css/style.css
> +    position: sticky !important;
Yes il faut le !important, j'ai rajouter le 11.5em dans l'id et retirer dans le inline-style

2022-05-17 08:35 UTC, Lucaversace commented on assets/css/style.css
> +    margin: 0 !important;
yes, c'est une class sur une balise <p>

2022-05-17 08:36 UTC, Lucaversace commented on assets/css/style.css
> +    box-shadow: 0 5px 30px rgba(0, 0, 0, 0.1);
Oui

2022-05-18 12:46 UTC, hubergerard requested changes

2022-05-18 12:46 UTC, hubergerard commented on .jekyll-cache/Jekyll/Cache/Jekyll--Cache/b7/9606fb3afea5bd1609ed40b622142f1c98125abcfe89a76a661b0e8e343910
> +I"%{"source"=>"/Users/lucabento-versace/Desktop/Codewise/sites/blog-codewise", "destination"=>"/Users/lucabento-versace/Desktop/Codewise/sites/blog-codewise/_site", "collections_dir"=>"", "cache_
Supprimer ce fichier de la PR

2022-06-02 07:26 UTC, merged